export const nodes = [
  {
    _hasContent: false,
    deadline: new Date(2020, 1, 15),
    id: '0',
    isComplete: true,
    name: 'Operating System',
    nodes: null,
    type: 'SETUP',
  },
  {
    _hasContent: false,
    deadline: new Date(2020, 1, 17),
    id: '1',
    isComplete: true,
    name: 'VSCode',
    nodes: [],
    type: 'SETUP',
  },
  {
    _hasContent: true,
    deadline: new Date(2020, 2, 28),
    id: '2',
    isComplete: true,
    name: 'JavaScript',
    nodes: [
      {
        _hasContent: true,
        deadline: new Date(2020, 2, 20),
        id: '22',
        isComplete: true,
        name: 'Data Types',
        nodes: [
          {
            _hasContent: false,
            deadline: new Date(2020, 2, 18),
            id: '221',
            isComplete: true,
            name: 'Strings',
            nodes: null,
            type: 'LEARN',
          },
          {
            _hasContent: false,
            deadline: new Date(2020, 2, 19),
            id: '222',
            isComplete: true,
            name: 'Numbers',
            nodes: null,
            type: 'LEARN',
          },
        ],
        type: 'LEARN',
      },
      {
        _hasContent: true,
        deadline: new Date(2020, 2, 22),
        id: '23',
        isComplete: true,
        name: 'Objects',
        nodes: [
          {
            _hasContent: false,
            deadline: new Date(2020, 2, 20),
            id: '231',
            isComplete: true,
            name: 'Object Methods',
            nodes: null,
            type: 'LEARN',
          },
          {
            _hasContent: false,
            deadline: new Date(2020, 2, 21),
            id: '232',
            isComplete: true,
            name: 'Garbage Collection',
            nodes: null,
            type: 'LEARN',
          },
        ],
        type: 'LEARN',
      },
      {
        _hasContent: false,
        deadline: new Date(2020, 2, 23),
        id: '24',
        isComplete: true,
        name: 'Code Style',
        nodes: [],
        type: 'LEARN',
      },
    ],
    type: 'LEARN',
  },
  {
    _hasContent: true,
    deadline: new Date(2020, 3, 8),
    id: '3',
    isComplete: false,
    name: 'React',
    nodes: [
      {
        _hasContent: false,
        deadline: new Date(2020, 3, 1),
        id: '31',
        isComplete: true,
        name: 'Create React App',
        nodes: null,
        type: 'SETUP',
      },
      {
        _hasContent: false,
        deadline: new Date(2020, 3, 1),
        id: '32',
        isComplete: true,
        name: 'JSX',
        nodes: null,
        type: 'LEARN',
      },
      {
        _hasContent: false,
        deadline: new Date(2020, 4, 1),
        id: '33',
        isComplete: false,
        name: 'Components',
        nodes: [],
        type: 'LEARN',
      },
      {
        _hasContent: false,
        deadline: new Date(2020, 5, 1),
        id: '34',
        isComplete: false,
        name: 'Props',
        nodes: null,
        type: 'LEARN',
      },
      {
        _hasContent: false,
        deadline: new Date(2020, 6, 1),
        id: '35',
        isComplete: false,
        name: 'State',
        nodes: [
          {
            _hasContent: false,
            deadline: new Date(2020, 7, 1),
            id: '351',
            isComplete: true,
            name: 'Remote State',
            nodes: [],
            type: 'LEARN',
          },
          {
            _hasContent: false,
            deadline: new Date(2020, 7, 1),
            id: '352',
            isComplete: false,
            name: 'Local State',
            nodes: [],
            type: 'LEARN',
          },
        ],
        type: 'LEARN',
      },
    ],
    type: 'LEARN',
  },
  {
    _hasContent: false,
    deadline: new Date(2020, 4, 28),
    id: '4',
    isComplete: false,
    name: 'Git',
    nodes: [],
    type: 'SETUP',
  },
  {
    _hasContent: true,
    deadline: new Date(2020, 5, 18),
    id: '5',
    isComplete: true,
    name: 'Node',
    nodes: [
      {
        _hasContent: false,
        deadline: new Date(2020, 5, 10),
        id: '51',
        isComplete: false,
        name: 'Express',
        nodes: null,
        type: 'LEARN',
      },
    ],
    type: 'LEARN',
  },
  {
    _hasContent: true,
    deadline: new Date(2020, 6, 30),
    id: '6',
    isComplete: false,
    name: 'GraphQL',
    nodes: [
      {
        _hasContent: true,
        deadline: new Date(2020, 6, 28),
        id: '61',
        isComplete: false,
        name: 'Queries and Mutations',
        nodes: [
          {
            _hasContent: false,
            deadline: new Date(2020, 6, 20),
            id: '611',
            isComplete: false,
            name: 'Fields',
            nodes: null,
            type: 'LEARN',
          },
          {
            _hasContent: false,
            deadline: new Date(2020, 6, 21),
            id: '612',
            isComplete: false,
            name: 'Arguments',
            nodes: null,
            type: 'LEARN',
          },
          {
            _hasContent: false,
            deadline: new Date(2020, 6, 22),
            id: '613',
            isComplete: false,
            name: 'Aliases',
            nodes: null,
            type: 'LEARN',
          },
          {
            _hasContent: true,
            deadline: new Date(2020, 6, 23),
            id: '614',
            isComplete: false,
            name: 'Fragments',
            nodes: [
              {
                _hasContent: false,
                deadline: new Date(2020, 6, 23),
                id: '6141',
                isComplete: false,
                name: 'Inline Fragments',
                nodes: null,
                type: 'LEARN',
              },
            ],
            type: 'LEARN',
          },
          {
            _hasContent: false,
            deadline: new Date(2020, 6, 24),
            id: '615',
            isComplete: false,
            name: 'Variables',
            nodes: null,
            type: 'LEARN',
          },
          {
            _hasContent: false,
            deadline: new Date(2020, 6, 25),
            id: '616',
            isComplete: false,
            name: 'Directives',
            nodes: null,
            type: 'LEARN',
          },
        ],
        type: 'LEARN',
      },
    ],
    type: 'LEARN',
  },
]

export const columns = [
  { label: 'Task', renderCell: (item) => <a href={'#'}> {item.name} </a> },
  {
    label: 'Deadline',
    renderCell: (item) =>
      item.deadline.toLocaleDateString('en-US', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
      }),
  },
  { label: 'Type', renderCell: (item) => item.type },
  {
    label: 'Complete',
    renderCell: (item) => item.isComplete.toString(),
  },
  { label: 'Tasks', renderCell: (item) => item.nodes?.length },
]
